### ISSUE TITLE
This stopped working

### ISSUE THREAD

**Issue by GELA-99** [RileyXX/MeijerAutoCouponClipper#1]
I get an error when using this now.

**Comment by RileyXX** [comment]
I made some updates recently that seems to have broken a portion of the code in some circumstances. I have updated the tool so it should be working now. If you still have problems let me know and I will try my best to help!

**Comment by GELA-99** [comment]
Works again!  Thanks!

**Comment by RileyXX** [comment]
Thanks for confirming!
